# Generated by Django 5.1.7 on 2025-04-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('manager', 'Manager'), ('executor', 'Executor')], max_length=10),
        ),
        migrations.DeleteModel(
            name='ProjectRole',
        ),
    ]
